[project]
name = "nih-grants"
version = "0.1.0"
description = "Metrics for NIH funding from open sources"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scholarly",
    "pandas",
    "polars>=1.26.0",
    "fastexcel>=0.13.0",
]
